# Generated by Django 4.0 on 2021-12-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaf',
            old_name='bod',
            new_name='body',
        ),
    ]
